export const errorsMessages ={

    PRODUCT_NOT_FOUND:"Product not found",
    PRODUCT_ALREADY_EXISTS: "Product already exists",
    CART_NOT_FOUND:"Cart not foundESTEEEEEE",
    CART_ALREADY_EXISTS: "Cart already exists",
    INVALID_CREDENTIALS: " Invalid credentials",
    USER_NOT_FOUND:"User not found ",
    USER_ALREADY_EXISTS: "User already exists ",
    MISSING_DATA: "Some data is missing",
    OID_INVALID_FORMAT:"Object id invalid format",

}

export const ErrorName = {
    PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
    MISSING_DATA: "MISSING_DATA",
    OID_INVALID_FORMAT:"OID_INVALID_FORMAT",
    CART_NOT_FOUND: "CART_NOT_FOUND",
    CART_OR_PRODUCT_NOT_FOUND: "CART_OR_PRODUCT_NOT_FOUND",
    CART_ALREADY_EXISTS: "CART_ALREADY_EXISTS",
    PRODUCT_ALREADY_EXISTS: "PRODUCT_ALREADY_EXISTS",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS", 
    USER_NOT_FOUND: "USER_NOT_FOUND",
    USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
}